version: 2
updates:
  # Pub dependencies
  - package-ecosystem: "pub"
    directories:
      - packages/**/*
      - modules/**/*
      - integrations/**/*
      - templates/serverpod_templates
      - tools/serverpod_cli
    schedule:
      interval: "weekly"
    versioning-strategy: "widen"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "tools/serverpod_vs_code_extension"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5