name: benchmark_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_client: 3.0.0-alpha.1

# dependency_overrides: 
#   serverpod_client: 
#     path: /Users/alex/repos/serverpod/main/packages/serverpod_client 
#   serverpod_serialization: 
#     path: /Users/alex/repos/serverpod/main/packages/serverpod_serialization 
