name: benchmark_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 3.0.0-alpha.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: ^1.25.5
  serverpod_test: 3.0.0-alpha.1

# dependency_overrides: 
#   serverpod: 
#     path: /Users/alex/repos/serverpod/main/packages/serverpod 
#   serverpod_serialization: 
#     path: /Users/alex/repos/serverpod/main/packages/serverpod_serialization 
#   serverpod_shared: 
#     path: /Users/alex/repos/serverpod/main/packages/serverpod_shared 
#   serverpod_test: 
#     path: /Users/alex/repos/serverpod/main/packages/serverpod_test 
#   serverpod_lints: 
#     path: /Users/alex/repos/serverpod/main/packages/serverpod_lints 
