# TEMPLATE

name: serverpod_auth_server
description: Serverpod authentication server module.
version: VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: VERSION
  serverpod_serialization: VERSION
  crypto: ^3.0.2
  email_validator: ^2.1.17
  firebase_admin: ^0.2.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  http: ">=0.13.0 <2.0.0"
  image: ^4.0.15
  jose: ^0.3.3

dev_dependencies:
  serverpod_lints: VERSION

dependency_overrides: #--CONDITIONALLY_REMOVE_LINE--#
  serverpod: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_serialization: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_serialization #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_lints: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_lints #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_service_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_service_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_shared: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_shared #--CONDITIONALLY_REMOVE_LINE--#